help :-
	write('Daftar Command : '),nl,
	write('1. start : Permainan dimulai. Hanya '),nl,
	write('2. map : Menampilkan peta beserta posisi pemain saat ini.'),nl,
	write('3. look : Menampilkan peta 3x3 yang lebih detil.'),nl,
	write('4. n : Bergerak kearah Utara(atas).'),nl,
	write('5. e : Bergerak kearah Timur(kanan).'),nl,
	write('6. w : Bergerak kearah Barat(kiri).'),nl,
	write('7. s : Bergerak kearah Selatan(bawah).'),nl,
	write('8. quit : Keluar dari permainan.'),nl,
	write('9. take(object) : Mengambil object pada petak.'),nl,
	write('10. drop(object) : Membuang sebuah object dari inventory.'),nl,
	write('11. use(object) : Menggunakan sebuah object yang dalam inventori.'),nl,
	write('12. attack : Menyerang enemy dalam petak sama.'),nl,
	write('13. status : Melihat status diri.'),nl,
	write('14. save(filename) : Menyimpan permainan pemain.'),nl,
	write('15. loads(filename) : Membuka save-an pemain.'),nl,
	write('16. help : Menampilkan ini lagi.'),nl,
  write('Catatan : Semua command di atas diakhiri titik (Misal : "help.")'), nl, !.
